# Generated by Django 2.2.4 on 2019-09-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tivix_posts', '0002_auto_20190925_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
